#!/usr/bin/env bash
set -ouex pipefail
. /ctx/lib.sh
log "Layering RPMs"

dnf_install \
    cosign \
    audit \
    usbguard \
    pam \
    firewalld \
    chrony \
    greetd \
    greetd-tuigreet \
    sway \
    swaylock \
    swayidle \
    swaybg \
    waybar \
    mako \
    rofi \
    grim \
    slurp \
    wl-clipboard \
    brightnessctl \
    playerctl \
    polkit-gnome \
    pipewire \
    pipewire-pulseaudio \
    pipewire-jack-audio-connection-kit \
    wireplumber \
    easyeffects \
    NetworkManager-wifi \
    NetworkManager-wireguard \
    wireguard-tools \
    bluez \
    blueman \
    fwupd \
    fprintd \
    bolt \
    pcsc-lite \
    pcsc-lite-ccid \
    yubikey-personalization \
    yubikey-manager \
    flatpak \
    distrobox \
    podman \
    just \
    git \
    vim \
    zsh \
    util-linux-user \
    bind-utils \
    bc \
    perf \
    inotify-tools \
    lm_sensors \
    smartmontools \
    dmidecode \
    ethtool \
    hdparm \
    nvme-cli \
    sbctl \
    sysstat \
    tcpdump \
    wireshark-cli \
    udisks2 \
    gvfs \
    devmon \
    google-noto-fonts-common \
    google-noto-emoji-fonts \
    jetbrains-mono-fonts \
    cabin-fonts \
    plymouth \
    plymouth-plugin-script
