# Borders
default_border normal 2
default_floating_border normal 2
titlebar_padding 3
title_align center

# Colors (gruvbox dark)
set $bg-color          #282828
set $inactive-bg-color #222222
set $text-color        #ffffff
set $inactive-text     #ffffff
set $urgent-bg-color   #ea6962

# class                 border             background         text            indicator
client.focused          $bg-color          $bg-color          $text-color     $bg-color
client.unfocused        $inactive-bg-color $inactive-bg-color $inactive-text  $inactive-bg-color
client.focused_inactive $inactive-bg-color $inactive-bg-color $inactive-text  $inactive-bg-color
client.urgent           $urgent-bg-color   $urgent-bg-color   $text-color     $urgent-bg-color

# Font
font pango:JetBrainsMono Nerd Font 10

# Cursor
seat * xcursor_theme Adwaita 16

# XWayland
xwayland enable
