RuleFile=/etc/usbguard/rules.conf
ImplicitPolicyTarget=block
PresentDevicePolicy=apply-policy
PresentControllerPolicy=apply-policy
InsertedDevicePolicy=apply-policy
IPCAllowedUsers=root
IPCAllowedGroups=wheel
DeviceManagerBackend=uevent
